controller_manager:
  ros__parameters:
    update_rate: 50

    # Joint state broadcaster
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    # Differential drive controller
    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController
      left_wheel: left_wheel_joint
      right_wheel: right_wheel_joint
      wheel_separation: 0.30
      wheel_radius: 0.05
      publish_rate: 50
      base_frame_id: base_link
      odom_frame_id: odom
      enable_odom_tf: true
      use_stamped_vel: false
      open_loop: false
      cmd_vel_timeout: 0.5
      velocity_rolling_window_size: 10
      linear.x.has_velocity_limits: true
      linear.x.max_velocity: 0.6
      linear.x.min_velocity: -0.6
      angular.z.has_velocity_limits: true
      angular.z.max_velocity: 1.5
      angular.z.min_velocity: -1.5
